"""empty message

Revision ID: 083ca022f72e
Revises: 07976ac359a0
Create Date: 2022-10-11 01:19:25.814127

"""

# revision identifiers, used by Alembic.
revision = '083ca022f72e'
down_revision = '07976ac359a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
