"""empty message

Revision ID: 09bb6f24f1fd
Revises: 4c7dcbd5f1a3
Create Date: 2022-10-20 18:25:01.214998

"""

# revision identifiers, used by Alembic.
revision = '09bb6f24f1fd'
down_revision = '4c7dcbd5f1a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    
    # ### end Alembic commands ###
