"""empty message

Revision ID: 2250bc9afa66
Revises: 0c0c4b757ae6
Create Date: 2022-10-20 16:27:15.364175

"""

# revision identifiers, used by Alembic.
revision = '2250bc9afa66'
down_revision = '0c0c4b757ae6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
