"""empty message

Revision ID: 4aae63daefe9
Revises: 790fe7439784
Create Date: 2022-09-28 21:30:49.879171

"""

# revision identifiers, used by Alembic.
revision = '4aae63daefe9'
down_revision = '790fe7439784'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
