"""empty message

Revision ID: 4c7dcbd5f1a3
Revises: afced8001ee8
Create Date: 2022-10-20 18:21:58.034350

"""

# revision identifiers, used by Alembic.
revision = '4c7dcbd5f1a3'
down_revision = 'afced8001ee8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'auther_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('auther_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['auther_id'], ['id'])
    # ### end Alembic commands ###
