"""empty message

Revision ID: a87c37788877
Revises: 09bb6f24f1fd
Create Date: 2022-10-20 21:40:44.374172

"""

# revision identifiers, used by Alembic.
revision = 'a87c37788877'
down_revision = '09bb6f24f1fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'auther_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('auther_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['auther_id'], ['id'])
    # ### end Alembic commands ###
