"""empty message

Revision ID: abb12c9878a0
Revises: 083ca022f72e
Create Date: 2022-10-11 01:39:31.939043

"""

# revision identifiers, used by Alembic.
revision = 'abb12c9878a0'
down_revision = '083ca022f72e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
