"""empty message

Revision ID: afced8001ee8
Revises: c4bec741abb4
Create Date: 2022-10-20 18:15:10.815654

"""

# revision identifiers, used by Alembic.
revision = 'afced8001ee8'
down_revision = 'c4bec741abb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
  pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('auther_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['auther_id'], ['id'])
    # ### end Alembic commands ###
