"""empty message

Revision ID: c4bec741abb4
Revises: 2250bc9afa66
Create Date: 2022-10-20 16:57:27.505459

"""

# revision identifiers, used by Alembic.
revision = 'c4bec741abb4'
down_revision = '2250bc9afa66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
